version: '3.7'

services:
  app:
    image: app-dev:latest
    build: ./
    ports:
      - "5443:5443"
      - "9229:9229"
    environment:
      NODE_ENV: development
      APP_PORT: 5443
    logging:
      driver: json-file
      options:
        mode: non-blocking
        max-buffer-size: '4m'
    volumes:
      - ~/dev/secrets:/run/secrets
    command: ["node", "--inspect=0.0.0.0:9229", "--trace-sync-io", "server.js"]